version: "3.9"
services:
  # airline-api:
  #   build: ../airline-backend
  #   restart: always
  #   ports:
  #     - 8081:8081
  db-user:
    image: mysql:8-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userdb
    volumes:
      - ./import-catalog.sql:/docker-entrypoint-initdb.d/import-catalog.sql
    ports:
      - "3308:3306"
  db-accommodation:
    image: mysql:8-debian
    restart: always
    environment:
      - MYSQL_DATABASE=accommodationdb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./import-catalog-acc.sql:/docker-entrypoint-initdb.d/import-catalog-acc.sql
    ports:
      - "3309:3306"
  rabbitmq:
    image: rabbitmq:3.9.11-management
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  notification-api:
    build: ../notification-microservice
    restart: always
    ports:
      - "8088:8088"
      - "9088:9088"  
  # acommodation-api:
  #   build: ../accommodation-microservice
  #   restart: always
  #   ports:
  #     - 8084:8084
  # user-api:
  #   build: ../user-microservice
  #   restart: always
  #   ports:
  #     - 8083:8083
