version: "3.9"
services:
  # airline-api:
  #   build: ../airline-backend
  #   restart: always
  #   ports:
  #     - 8081:8081
  db:
    image: mysql:8-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking
    volumes:
      - ./import-catalog.sql:/docker-entrypoint-initdb.d/import-catalog.sql
    ports:
      - "3308:3306"
  acommodation-api:
    build: ../accommodation-microservice
    restart: always
    ports:
      - 8084:8084
  # user-api:
  #   build: ../user-microservice
  #   restart: always
  #   ports:
  #     - 8083:8083
