global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "accommodation-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["accommodation-api:8084"]
        labels:
          application: "Accommodation Service Application"
  - job_name: "gateway-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway-api:8082"]
        labels:
          application: "Gateway Service Application"
  - job_name: "reservation-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["reservation-api:8085"]
        labels:
          application: "Reservation Service Application"
  - job_name: "user-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-api:8083"]
        labels:
          application: "User Service Application"
